{
 "title": "Alle Einsätze",
 "time": { "from": "2019-05-16T22:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Zeit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nNOW() AS \"time\",\nSUM(EXTRACT(EPOCH FROM(ende - start)))/3600 AS value\nFROM einsaetze\nWHERE\n  $__timeFilter(start)"
    }
   ]
  },
  {
   "title": "Eingesetzt in %",
   "type": "stat",
   "description": "Wie oft % im Einsatz",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  AVG(eingesetzt::int)*100 AS \"In Auswahl\"\nFROM einsaetze\nWHERE\n  $__timeFilter(start)"
    }
   ]
  },
  {
   "title": "Einsätze gesamt",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nCOUNT(eingesetzt::int) AS \"Insgesamt (Anzahl)\"\nFROM einsaetze"
    }
   ]
  },
  {
   "title": "Eingesetzt in Auswahl",
   "type": "stat",
   "description": "Wie oft wirklich im Einsatz im ausgewählten Zeitraum",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  NOW() AS \"time\",\n  SUM(CASE WHEN eingesetzt THEN 1 END) AS \"Eingesetzt\",\n  SUM(CASE WHEN NOT eingesetzt THEN 1 END) AS \"In Bereitstellung\"\nFROM einsaetze\nWHERE\n  $__timeFilter(start)"
    }
   ]
  },
  {
   "title": "Einsatzarten",
   "type": "grafana-piechart-panel",
   "description": "Art der Einsätze als Pie Chart",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\", art,\n  count(*) hits\nFROM einsaetze\nWHERE\n  $__timeFilter(start)\nGROUP BY art"
    }
   ]
  },
  {
   "title": "Funktionen",
   "type": "grafana-piechart-panel",
   "description": "Funktionen im Einsatz als Pie Chart",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\", funktion,\n  count(*) hits\nFROM einsaetze\nWHERE\n  $__timeFilter(start)\nGROUP BY funktion"
    }
   ]
  },
  {
   "title": "Einsatzmittel",
   "type": "grafana-piechart-panel",
   "description": "Gefahrenes Fahrzeug",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\", einsatzmittel,\n  COUNT(*) hits\nFROM einsaetze\nWHERE\n  $__timeFilter(start) AND\n  einsatzmittel IS NOT null\nGROUP BY einsatzmittel"
    }
   ]
  },
  {
   "title": "Einsätze / Monat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Anzahl" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('month', start) AS \"time\",\n  count(1) as Einsätze\nFROM einsaetze\nWHERE\n  $__timeFilter(start)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Einsätze",
   "type": "table",
   "description": "Alle Einsätze",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT \n  nummer, start AS \"time\",\n  ende, ort, art, funktion, eingesetzt, alarmierung, bemerkungen\nFROM einsaetze\nwhere\n  $__timeFilter(start)\nORDER BY start"
    }
   ]
  }
 ]
}