{
 "title": "Einsätze",
 "time": { "from": "2019-05-16T22:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Zeit",
   "type": "stat",
   "description": "Zeit in Stunden in Auswahl",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nNOW() AS \"time\",\nSUM(EXTRACT(EPOCH FROM(ende - start)))/3600 AS value\nFROM einsaetze\nWHERE\n  $__timeFilter(start)"
    }
   ]
  },
  {
   "title": "Einsätze",
   "type": "stat",
   "description": "Einsätze im gewählten Zeitraum",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nNOW() AS \"time\",\nCOUNT(eingesetzt::int) AS \"Teilgenommen (Anzahl)\"\nFROM einsaetze\nWHERE\n  $__timeFilter(start)"
    }
   ]
  },
  {
   "title": "Eingesetzt in %",
   "type": "gauge",
   "description": "Wie oft % im Einsatz",
   "gridPos": { "h": 8, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  AVG(eingesetzt::int)*100 AS \"In Auswahl\"\nFROM einsaetze\nWHERE\n  $__timeFilter(start)"
    }
   ]
  },
  {
   "title": "Eingesetzt in Auswahl",
   "type": "piechart",
   "description": "Wie oft wirklich im Einsatz im ausgewählten Zeitraum",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  NOW() AS \"time\",\n  SUM(CASE WHEN eingesetzt THEN 1 END) AS \"Eingesetzt\",\n  SUM(CASE WHEN NOT eingesetzt THEN 1 END) AS \"In Bereitstellung\"\nFROM einsaetze\nWHERE\n  $__timeFilter(start)"
    }
   ]
  },
  {
   "title": "PA-Typen",
   "type": "piechart",
   "description": "PA-Typen",
   "gridPos": { "h": 8, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  NOW() AS \"time\",\r\n  count(agt) filter (where agt='PA') AS \"PA\",\r\n  count(agt) filter (where agt='Filter') AS \"Filter\"\r\nFROM einsaetze\r\nWHERE\r\n  $__timeFilter(start)\r\n  AND agt is not null;\r\n"
    }
   ]
  },
  {
   "title": "PA-Einsätze",
   "type": "piechart",
   "description": "PA-Angeschnauft",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\",\n  count(angeschnauft) filter (WHERE angeschnauft='true') AS \"Angeschnauft\",\n  count(angeschnauft) filter (WHERE angeschnauft='false') AS \"Nicht Angeschnauft\"\nFROM einsaetze\nWHERE\n  $__timeFilter(start)\n  AND angeschnauft is NOT NULL;\n\n"
    }
   ]
  },
  {
   "title": "Einsatzarten",
   "type": "piechart",
   "description": "Art der Einsätze als Pie Chart",
   "gridPos": { "h": 17, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\", art,\n  count(*) hits\nFROM einsaetze\nWHERE\n  $__timeFilter(start)\nGROUP BY art"
    }
   ]
  },
  {
   "title": "Funktionen",
   "type": "piechart",
   "description": "Funktionen im Einsatz als Pie Chart",
   "gridPos": { "h": 17, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\", funktion,\n  count(*) hits\nFROM einsaetze\nWHERE\n  $__timeFilter(start)\nGROUP BY funktion"
    }
   ]
  },
  {
   "title": "Einsatzmittel",
   "type": "piechart",
   "description": "Gefahrenes Fahrzeug",
   "gridPos": { "h": 17, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\", einsatzmittel,\n  COUNT(*) hits\nFROM einsaetze\nWHERE\n  $__timeFilter(start) AND\n  einsatzmittel IS NOT null\nGROUP BY einsatzmittel"
    }
   ]
  },
  {
   "title": "Einsatzstichwort",
   "type": "piechart",
   "description": "Alarmiertes Stichwort",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\", alarmierung,\n  COUNT(*) hits\nFROM einsaetze\nWHERE\n  $__timeFilter(start) AND\n  alarmierung IS NOT null\nGROUP BY alarmierung"
    }
   ]
  },
  {
   "title": "Einsätze / Monat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('month', start) AS \"time\",\n  count(1) as Einsätze\nFROM einsaetze\nWHERE\n  $__timeFilter(start)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Einsätze",
   "type": "table",
   "description": "Alle Einsätze",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT \n  nummer, start AS \"time\",\n  ende, ort, art, funktion, agt, einsatzmittel, eingesetzt, alarmierung, bemerkungen\nFROM einsaetze\nwhere\n  $__timeFilter(start)\nORDER BY start"
    }
   ]
  }
 ]
}