{
 "title": "Übungen / Ausbildungen",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Übungen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Übungsthema",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\", thema,\n  count(*) hits\nFROM uebungen\nWHERE\n  $__timeFilter(start)\nGROUP BY thema"
    }
   ]
  },
  {
   "title": "Übungsort",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\", ort,\n  count(*) hits\nFROM uebungen\nWHERE\n  $__timeFilter(start)\nGROUP BY ort"
    }
   ]
  },
  {
   "title": "Übungszeit",
   "type": "stat",
   "description": "Mit Übungen verbrachte Zeit in h",
   "gridPos": { "h": 7, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nNOW() AS \"time\",\nSUM(EXTRACT(EPOCH FROM(ende - start)))/3600 AS value\nFROM uebungen\nWHERE\n  $__timeFilter(start)"
    }
   ]
  },
  {
   "title": "Übungen gesamt",
   "type": "stat",
   "description": "Gesamtzahl teilgenommener Übungen",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nCOUNT(teilnahme::int) AS \"Insgesamt (Anzahl)\"\nFROM uebungen"
    }
   ]
  },
  {
   "title": "Teilnahme in %",
   "type": "stat",
   "description": "Übungsteilnahme in %",
   "gridPos": { "h": 7, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  AVG(teilnahme::int)*100 AS \"In Auswahl\"\nFROM uebungen\nWHERE\n  $__timeFilter(start)"
    }
   ]
  },
  {
   "title": "Teilnahmen in Auswahl",
   "type": "stat",
   "description": "Teilnahmen in dem ausgewählten Zeitraum",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  NOW() AS \"time\",\n  SUM(CASE WHEN teilnahme THEN 1 END) AS \"Teilgenommen\",\n  SUM(CASE WHEN NOT teilnahme THEN 1 END) AS \"Nicht teilgenommen\"\nFROM uebungen\nWHERE\n  $__timeFilter(start)"
    }
   ]
  },
  {
   "title": "Übungsteilnahme",
   "type": "table",
   "description": "Übungsteilnahme in Auswahl",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM\n  uebungen\nWHERE\n  $__timeFilter(start)\nORDER BY nummer DESC\n"
    }
   ]
  },
  { "title": "Ausbildungen", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Ausbildungsort",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 29 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\", ort,\n  count(*) hits\nFROM ausbildung\nWHERE\n  $__timeFilter(start)\nGROUP BY ort"
    }
   ]
  },
  {
   "title": "Ausbildungsthema",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 29 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\", thema,\n  count(*) hits\nFROM ausbildung\nWHERE\n  $__timeFilter(start)\nGROUP BY thema"
    }
   ]
  },
  {
   "title": "Zeit",
   "type": "stat",
   "description": "Zeit (h) in Auswahl",
   "gridPos": { "h": 8, "w": 3, "x": 16, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nNOW() AS \"time\",\nSUM(EXTRACT(EPOCH FROM(ende - start)))/3600 AS value\nFROM ausbildung\nWHERE\n  $__timeFilter(start)"
    }
   ]
  },
  {
   "title": "Ausbildungstage",
   "type": "stat",
   "description": "Ausbildungstage in Auswahl",
   "gridPos": { "h": 8, "w": 4, "x": 19, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nCOUNT(*) AS \"Insgesamt (Anzahl)\"\nFROM ausbildung"
    }
   ]
  },
  {
   "title": "Ausbildungen",
   "type": "table",
   "description": "Ausbildungen in Auswahl",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM\n  ausbildung\nWHERE\n  $__timeFilter(start)\nORDER BY nummer DESC\n"
    }
   ]
  }
 ]
}