#!/bin/bash
#
# variablen
hostname=localhost
username=root
database=feuerwehr
d=`date +%Y-%m-%d`

### Text Output
echo "Wöchentliche Prüfung der Tauglichkeit, G26 und Belastungsübung."
echo ""
echo "Die G 26.3 läuft bei folgenden Kameraden innerhalb 3 Monaten ab:"
echo "(Hier gelistete AGT sollten informiert werden, einen Termin beim Arbeitsmediziner zu vereinbaren. Kostenübernahme von Torsten ist zu beauftragen.)"
psql -P pager=off -d $database -U $username -c "SELECT name, vorname, g26bis, patauglich FROM feuerwehr.atemschutz WHERE agtaktiv = true AND g26bis <= CURRENT_DATE + INTERVAL '3 months';"

echo "Die G 26.3 ist bei folgenden Kameraden abgelaufen:"
echo "(Hier gelistete AGT wurden auf untauglich gesetzt. AGT-Namensschild ist zu entfernen!)"
psql -P pager=off -d $database -U $username -c "SELECT name, vorname, g26bis, patauglich FROM feuerwehr.atemschutz WHERE agtaktiv = true AND g26bis < CURRENT_DATE;"
psql -P pager=off -d $database -U $username -c "UPDATE feuerwehr.atemschutz SET patauglich = FALSE WHERE g26bis < CURRENT_DATE;"

echo "Die Belastungsubung wurde von folgenden AGT nicht innerhalb diesen oder letzten Jahres abgelegt:"
echo "(Hier gelistete AGT wurden auf untauglich gesetzt. AGT-Namensschild ist zu entfernen!)"
psql -P pager=off -d $database -U $username -c "SELECT name, vorname, lastbelastung, patauglich FROM feuerwehr.atemschutz WHERE agtaktiv = true AND EXTRACT(YEAR FROM lastbelastung) NOT IN (EXTRACT(YEAR FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE) - 1);"
psql -P pager=off -d $database -U $username -c "UPDATE feuerwehr.atemschutz SET patauglich = FALSE WHERE EXTRACT(YEAR FROM lastbelastung) NOT IN (EXTRACT(YEAR FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE) - 1);"

echo "Prüfe die Tauglichkeit der AGT und setze taugliche AGT auf tauglich.."
psql -P pager=off -d $database -U $username -c "UPDATE feuerwehr.atemschutz SET patauglich = TRUE WHERE EXTRACT(YEAR FROM lastbelastung) IN (EXTRACT(YEAR FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE) - 1) AND g26bis > CURRENT_DATE;"

echo "Aktuell taugliche AGT (sortiert nach G 26.3 Ablauf):"
psql -P pager=off -d $database -U $username -c "SELECT name, vorname, g26bis, lastbelastung, patauglich FROM feuerwehr.atemschutz WHERE agtaktiv = TRUE AND EXTRACT(YEAR FROM lastbelastung) IN (EXTRACT(YEAR FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE) - 1) AND g26bis > CURRENT_DATE ORDER BY g26bis ASC;"

echo "Aktuell untaugliche AGT (sortiert nach G 26.3 Ablauf):"
psql -P pager=off -d $database -U $username -c "SELECT name, vorname, g26bis, lastbelastung, patauglich FROM feuerwehr.atemschutz WHERE agtaktiv = TRUE AND patauglich = FALSE ORDER BY g26bis ASC;"

echo "Anzahl aktuell tauglicher AGT:"
psql -P pager=off -d $database -U $username -c "SELECT COUNT(*) FROM feuerwehr.atemschutz WHERE agtaktiv = TRUE AND patauglich = TRUE;"

echo "Wöchentliche Prüfung der Tauglichkeit, G26 und Belastungsübung ist damit abgeschlossen."