#!/bin/bash
#
# variablen
hostname=localhost
username=root
database=feuerwehr
d=`date +%Y-%m-%d`

echo ""
echo "AGT entfernen"
echo "-------------"
echo ""

# einlesen der daten
echo "Vorname: "
read vorname
echo ""
echo "Nachname: "
read name
echo ""
echo "Aaah, $vorname $name soll gelöscht werden? Schade, aber na klar!"
#übersicht eingabe
echo "Das ist mir über den Kamerad bekannt:"
psql -P pager=off -d $database -U $username -c "SELECT * FROM $database.atemschutz WHERE vorname = '$vorname' AND name = '$name';"
echo "--------------------"
echo ""
# Frage ob aus DB entfernen
echo "Aus Datenbank löschen?: "
PS3='Bitte auswählen: '
options=("OK" "Nee, doch nicht!")
select save in "${options[@]}"
do
    case $save in
       	"OK")
       	  echo "Du hast $save ausgewählt."
       	  echo ""
       	  echo "Lösche $vorname $nachname aus der Datenbank.."
          psql -P pager=off -d $database -U $username -c "DELETE FROM $database.atemschutz WHERE vorname = '$vorname' AND name = '$name';"
          echo "Kamerad wurde gelöscht!"
          echo "----------------------"
          break
	  ;;
        "Nee, doch nicht!")
          echo "Breche ab und lösche nichts aus der Datenbank."
          break
          ;;
        *) echo "Ungültige Option: $REPLY";;
    esac
done
