#!/bin/bash
#
# variablen
hostname=localhost
username=root
database=feuerwehr
d=`date +%Y-%m-%d`

echo "+++ Nicely done, setze AGT auf tauglich +++"
echo ""
psql -P pager=off -h $hostname -d $database -U $username -c "UPDATE feuerwehr.atemschutz SET patauglich = TRUE WHERE EXTRACT(YEAR FROM lastbelastung) IN (EXTRACT(YEAR FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE) - 1) AND g26bis > CURRENT_DATE;"
echo "+++ AGT auf tauglich gesetzt +++"
echo ""
echo ""
echo "+--+ Aktuell taugliche AGT +--+"
psql -P pager=off -h $hostname -d $database -U $username -c "SELECT name, vorname, g26bis, lastbelastung, patauglich FROM feuerwehr.atemschutz WHERE agtaktiv = TRUE AND EXTRACT(YEAR FROM lastbelastung) IN (EXTRACT(YEAR FROM CURRENT_DATE), EXTRACT(YEAR FROM CURRENT_DATE) - 1) AND g26bis > CURRENT_DATE ORDER BY name ASC;"
psql -P pager=off -h $hostname -d $database -U $username -c "SELECT COUNT(*) FROM feuerwehr.atemschutz WHERE agtaktiv = TRUE AND patauglich = TRUE;"
