#!/bin/bash
#
# variablen
hostname=localhost
username=root
database=feuerwehr
d=`date +%Y-%m-%d`

echo "Letzte Ausbildung"
echo "-------------"
psql -P pager=off -d $database -U $username -c "SELECT * FROM $database.ausbildung ORDER BY nummer DESC LIMIT 1;"
echo ""
echo ""
echo "Neue Ausbildung"
echo "-------------"
echo ""

# einlesen der daten
echo "Ausbildung Nummer z.B. 4 : "
read nummer
echo ""
echo "Auswahl Datum:"
# auswahl Y/N ob aktueller Tag als Datum
while true; do
	read -p "Aktuellen Tag ($d) als Datum verwenden? (Yy/Nn): " yn
	case $yn in
		[Yy]* ) datum=$d; break;;
		[Nn]* ) datum=manual; break;;
		* ) echo "Antwort mit Y oder N!.";;
	esac
done
if [[ $datum = manual ]]
	then
		#funktion
		echo "Datum z.B. 2019-05-25 :"
		read datum
fi
echo ""
echo "Startzeit z.B. 04:57:17 :"
read beginnzeit
echo "Endzeit z.B. 04:57:17 :"
read endzeit
echo "Ort z.B. Woerth :"
read ort
echo "Thema (Truppmann/AGT/Sprechfunker/etc.): "
read thema
echo "Bemerkungen : "
read bemerkungen
echo ""

# übersicht eingegebene daten
echo "Übersicht Ausbildung:"
echo "--------------------"
echo "Nummer: $nummer"
echo "Beginn: $datum $beginnzeit"
echo "Ende: $datum $endzeit"
echo "Ort: $ort"
echo "Thema: $thema"
echo "Bemerkungen: $bemerkungen"
echo "--------------------"
echo ""

# Frage ob in DB schreiben
echo "In Datenbank schreiben?: "
PS3='Bitte auswählen: '
options=("OK" "Nee, doch nicht!")
select save in "${options[@]}"
do
    case $save in
        "OK")
            echo "Du hast $save ausgewählt."
	        echo ""		
	        echo "Schreibe Ausbildung in Datenbank.."
            psql -P pager=off -d $database -U $username -c "INSERT INTO $database.ausbildung (nummer,start,ende,ort,thema,bemerkungen) VALUES ('$nummer', '$datum $beginnzeit', '$datum $endzeit', '$ort', '$thema', '$bemerkungen');"
			# geschriebene daten von db lesen
			echo ""
			echo "Folgende Ausbildung erfolgreich in Datenbank geschrieben:"
			echo "----------------------"
			psql -P pager=off -d $database -U $username -c "SELECT * FROM $database.ausbildung WHERE nummer='$nummer';"
            break
            ;;
        "Nee, doch nicht!")
            echo "Breche ab und speichere nichts in die Datenbank."
            break
            ;;
        *) echo "Ungültige Option: $REPLY";;
    esac
done
