#!/bin/bash
#
# variablen
hostname=localhost
username=root
database=feuerwehr

echo "Letzter Einsatz"
echo "-------------"
psql $database $username << EOF
SELECT * FROM einsaetze ORDER BY nummer DESC LIMIT 1;
EOF
echo ""
echo ""
echo "Neuer Einsatz"
echo "-------------"
echo ""

# einlesen der daten
echo "Einsatz Nummer z.B. 104 : "
read nummer
echo "Startdatum z.B. 2019-05-25 :"
read beginn
echo "Startzeit z.B. 04:57:17 :"
read beginnzeit
echo "Enddatum z.B. 2019-05-25 :"
read ende
echo "Endzeit z.B. 04:57:17 :"
read endzeit
echo "Ort z.B. Woerth :"
read ort
echo "Art des Einsatzes (Brand/TH/Gefahrstoffe/Dienstleistung): "
read art
echo "Funktion z.B. (FEZ, TM, AGT, MA) : "
read funktion
echo "Einsatzmittel z.B. (HLF20, DLK, FEZ) :"
read einsatzmittel
echo "Im Einsatz (true/false) : "
read eingesetzt
echo "Alarmierung z.B. Brennt PKW : "
read alarmierung
echo "Bemerkungen : "
read bemerkungen
echo ""

# daten in db schreiben
echo "Schreibe Datensatz.."
echo "--------------------"
psql $database $username << EOF
INSERT INTO einsaetze (nummer,start,ende,ort,art,funktion,eingesetzt,alarmierung,bemerkungen,einsatzmittel) VALUES ('$nummer', '$beginn $beginnzeit', '$ende $endzeit', '$ort', '$art', '$funktion', '$eingesetzt', '$alarmierung', '$bemerkungen', '$einsatzmittel');
EOF

# geschriebene daten von db lesen
echo "Fertiiiig. Guck, hier:"
echo "----------------------"
psql $database $username << EOF
SELECT * FROM einsaetze WHERE nummer='$nummer';
EOF
