#!/bin/bash
#
# variablen
hostname=localhost
username=root
database=feuerwehr

echo "Letzter Einsatz"
echo "-------------"
psql -P pager=off -d $database -U $username -c "SELECT * FROM $database.einsaetze ORDER BY nummer DESC LIMIT 1;"
echo ""
echo ""
echo "Einsatz löschen"
echo "-------------"
echo ""

# einlesen der daten
echo "Einsatz Nummer z.B. 104 : "
read nummer
echo ""

# übersicht eingegebene daten
echo "Ausgewählter Einsatz zum löschen:"
echo "--------------------"
psql -P pager=off -d $database -U $username -c "SELECT * FROM $database.einsaetze WHERE nummer='$nummer';"
echo "--------------------"
echo ""

# Frage ob aus DB löschen
echo "Einsatz löschen?: "
PS3='Bitte auswählen: '
options=("OK" "Nee, doch nicht!")
select save in "${options[@]}"
do
    case $save in
        "OK")
            echo "Du hast $save ausgewählt."
            echo ""		
            echo "Lösche Einsatz aus Datenbank.."
            psql -P pager=off -d $database -U $username -c "DELETE FROM $database.einsaetze WHERE nummer='$nummer';"
            echo ""
            echo "Einsatz gelöscht"
            echo "----------------------"
            break
            ;;
        "Nee, doch nicht!")
            echo "Breche ab und lösche nichts aus der Datenbank."
            break
            ;;
        *) echo "Ungültige Option: $REPLY";;
    esac
done
