#!/bin/bash
#
# variablen
hostname=localhost
username=root
database=feuerwehr

echo "Letzter Einsatz"
echo "-------------"
psql $database $username << EOF
SELECT * FROM einsaetze ORDER BY nummer DESC LIMIT 1;
EOF
echo ""
echo ""
echo "Einsatz löschen"
echo "-------------"
echo ""

# einlesen der daten
echo "Einsatz Nummer z.B. 104 : "
read nummer

# daten in db schreiben
echo "Lösche Datensatz.."
echo "--------------------"
psql $database $username << EOF
DELETE FROM einsaetze WHERE nummer='$nummer';
EOF
