#!/bin/bash
#
# variablen
hostname=localhost
username=root
database=feuerwehr
d=`date +%Y-%m-%d`

echo ""
echo "Letzter Einsatz"
echo "-------------"
psql -P pager=off -d $database -U $username -c "SELECT * FROM $database.einsaetze ORDER BY nummer DESC LIMIT 1;"
echo ""
echo ""
echo "Neuer Einsatz"
echo "-------------"
echo ""

# einlesen der daten

# auswahl Y/N ob Einsatznummer Auto-Increment
while true; do
        read -p "Einsatznummer automatisch auf basis des letzten Einsatzes hochzählen? (Yy/Nn): " yn
        case $yn in
                [Yy]* ) 
			nummer=$(psql -P pager=off -d $database -U $username -c "SELECT nummer FROM $database.einsaetze ORDER BY nummer DESC LIMIT 1;" | head -3 | tail -1 | awk '{$1=$1};1')
			echo "Letzter Einsatz hatte Nummer $nummer"
			nummer=$((nummer+1))
			echo "Nutze $nummer als Einsatznummer für diesen Einsatz.";
			break;;
                [Nn]* ) 
			echo "Einsatz Nummer z.B. 104 : "
			read nummer; break;;
                * ) echo "Antwort mit Y oder N!.";;
        esac
done

echo "Auswahl Startdatum:"
# auswahl Y/N ob aktueller Tag als Datum
while true; do
	read -p "Aktuellen Tag ($d) als Startdatum verwenden? (Yy/Nn): " yn
	case $yn in
		[Yy]* ) beginn=$d; break;;
		[Nn]* ) beginn=manual; break;;
		* ) echo "Antwort mit Y oder N!.";;
	esac
done
if [[ $beginn = manual ]]
	then
		#funktion
		echo "Startdatum z.B. 2019-05-25 :"
		read beginn
fi

echo ""
echo "Startzeit z.B. 04:57:17 :"
read beginnzeit
echo ""

echo "Auswahl Enddatum:"
# auswahl Y/N ob aktueller Tag als Datum
while true; do
	read -p "Aktuellen Tag ($d) als Enddatum verwenden? (Yy/Nn): " yn
	case $yn in
		[Yy]* ) ende=$d; break;;
		[Nn]* ) ende=manual; break;;
		* ) echo "Antwort mit Y oder N!.";;
	esac
done
if [[ $ende = manual ]]
	then
		#funktion
		echo "Enddatum z.B. 2019-05-25 :"
		read ende
fi

echo ""
echo "Endzeit z.B. 04:57:17 :"
read endzeit
echo ""
echo "Ort z.B. Woerth :"
read ort
echo ""

echo "Art des Einsatzes: "
PS3='Bitte auswählen: '
options=("Brand" "TH" "Gefahrstoffe" "Dienstleistung")
select art in "${options[@]}"
do
    case $art in
        "Brand")
            echo "Du hast $art ausgewählt."
            break
            ;;
        "TH")
            echo "Du hast $art ausgewählt."
            break
            ;;
        "Gefahrstoffe")
            echo "Du hast $art ausgewählt."
            break
            ;;
        "Dienstleistung")
            echo "Du hast $art ausgewählt."
            break
            ;;            
        *) echo "Ungültige Option: $REPLY";;
    esac
done
echo ""
# auswahl Y/N ob im Einsatz
while true; do
	read -p "Im Einsatz? (Yy/Nn): " yn
	case $yn in
		[Yy]* ) eingesetzt="true"; break;;
		[Nn]* ) eingesetzt="false"; break;;
		* ) echo "Antwort mit Y oder N!.";;
	esac
done

echo ""
# nur dinge tun, wenn auch eingesetzt, sonst Bereitstellung befüllen
if [[ $eingesetzt = true ]]
	then
		#funktion
		echo "Funktion im Einsatz: "
		PS3='Bitte auswählen: '
		options=("TM" "AGT" "CSA" "FEZ" "MA" "GF" "EL")
		select funktion in "${options[@]}"
		do
			case $funktion in
				"TM")
					echo "Du hast $funktion ausgewählt."
					break
					;;
				"AGT")
					echo "Du hast $funktion ausgewählt."
					break
					;;
				"CSA")
					echo "Du hast $funktion ausgewählt."
					break
					;;
				"FEZ")
					echo "Du hast $funktion ausgewählt."
					break
					;;
				"MA")
					echo "Du hast $funktion ausgewählt."
					break
					;;            
				"GF")
					echo "Du hast $funktion ausgewählt."
					break
					;;            
				"EL")
					echo "Du hast $funktion ausgewählt."
					break
					;;            
				*) echo "Ungültige Option: $REPLY";;
			esac
		done
	  echo ""
	    # wenn funktion FEZ Einsatzmittel mit FEZ ausfüllen
	    if [[ $funktion = FEZ ]]
	      then
		einsatzmittel="FEZ"
	      else
			#einsatzmittel
			echo "Einsatzmittel im Einsatz: "
			PS3='Bitte auswählen: '
			options=("HLF20" "HLF10" "DLK" "MTF" "WLF" "WLF-K" "ELW" "GW-Mess" "MZF" "MZB")
			select einsatzmittel in "${options[@]}"
			do
				case $einsatzmittel in
					"HLF20")
						echo "Du hast $einsatzmittel ausgewählt."
						break
						;;
					"HLF10")
						echo "Du hast $einsatzmittel ausgewählt."
						break
						;;
					"DLK")
						echo "Du hast $einsatzmittel ausgewählt."
						break
						;;
					"MTF")
						echo "Du hast $einsatzmittel ausgewählt."
						break
						;;
					"WLF")
						echo "Du hast $einsatzmittel ausgewählt."
						break
						;;
					"WLF-K")
						echo "Du hast $einsatzmittel ausgewählt."
						break
						;;
					"ELW")
						echo "Du hast $einsatzmittel ausgewählt."
						break
						;;
					"GW-Mess")
						echo "Du hast $einsatzmittel ausgewählt."
						break
						;;
					"MZF")
						echo "Du hast $einsatzmittel ausgewählt."
						break
						;;
					"MZB")
						echo "Du hast $einsatzmittel ausgewählt."
						break
						;;
					*) echo "Ungültige Option: $REPLY";;
				esac
			done
	    fi
	else
		funktion="In Bereitstellung"
		einsatzmittel="In Bereitstellung"
fi

echo ""
# agt abfrage
if [[ $funktion = AGT ]]
        then
	  while true; do
      	  	read -p "Angeschnauft? (Yy/Nn): " ang
	  	case $ang in
		  	[Yy]* ) angeschnauft="true"; break;;
		  	[Nn]* ) angeschnauft="false"; break;;
	  	esac
	  done
	 # angeschnauft abfrage geraeteart
	if [[ $angeschnauft = true ]]
		then
			#agt
			echo "Geräteart im Einsatz: "
			PS3='Bitte auswählen: '
			options=("PA" "Filter")
			select agt in "${options[@]}"
			do
				case $agt in
					"PA")
						echo "Du hast $agt ausgewählt."
						break
						;;
					"Filter")
						echo "Du hast $agt ausgewählt."
						break
						;;
					*) echo "Ungültige Option: $REPLY";;
				esac
		done
	fi

fi

# csa abfrage
if [[ $funktion = CSA ]]
	then
	angeschnauft="true"
	# abfrage csa-art
	if [[ $angeschnauft = true ]]
		then
			#csa
			echo "CSA im Einsatz: "
			PS3='Bitte auswählen: '
			options=("CSA Form 2+Filter" "CSA Form 2+PA" "CSA Form 3")
			select agt in "${options[@]}"
			do
				case $agt in
					"CSA Form 2+Filter")
						echo "Du hast $agt ausgewählt."
						break
						;;
					"CSA Form 2+PA")
						echo "Du hast $agt ausgewählt."
						break
						;;
					"CSA Form 3")
						echo "Du hast $agt ausgewählt."
						break
						;;
					*) echo "Ungültige Option: $REPLY";;
				esac
			done
	fi
fi

echo ""
# abfrage einsatzstichwort je nach einsatzart gruppiert
if [[ $art == "Brand" ]]
	then
		#alarmierungbrand
		echo "Einsatzstichwort: "
		PS3='Bitte auswählen: '
		options=("Balkonbrand" "BMA Alarm" "Brand Allgemein" "Dachstuhlbrand" "Flächenbrand groß" "Flächenbrand klein" "Gartenhausbrand" "Gebäudebrand" "Grillbrand" "Holzstapelbrand" "Kaminbrand" "Kellerbrand" "LKW Brand" "Mülleimerbrand" "PKW Brand" "Privater Rauchmelder" "Rauchentwicklung im Freien unklar" "Rauchentwicklung im Gebäude unklar" "Wohnungsbrand" "Zimmerbrand" "Waldbrand")
		select alarmierung in "${options[@]}"
		do
			case $alarmierung in
				"Balkonbrand")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"BMA Alarm")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Brand Allgemein")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Dachstuhlbrand")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;                        
				"Flächenbrand groß")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;                        
				"Flächenbrand klein")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;                        
				"Gartenhausbrand")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;                        
				"Gebäudebrand")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;                        
				"Grillbrand")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;                        
				"Holzstapelbrand")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;                        
				"Kaminbrand")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;                        
				"Kellerbrand")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;                        
				"LKW Brand")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;                        
				"Mülleimerbrand")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;                        
				"PKW Brand")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;                        
				"Privater Rauchmelder")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;                        
				"Rauchentwicklung im Freien unklar")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;                        
				"Rauchentwicklung im Gebäude unklar")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;                        
				"Wohnungsbrand")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Zimmerbrand")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Waldbrand")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				*) echo "Ungültige Option: $REPLY";;
			esac
		done
fi

if [[ $art == "TH" ]]
	then
		#alarmierungth
		echo "Einsatzstichwort: "
		PS3='Bitte auswählen: '
		options=("Notfalltüröffnung" "Person eingeklemmt" "Person in Aufzug" "Person in Wasser" "Personensuche" "Schiffshavarie" "Tierrettung" "TH Allgemein" "Unterstützung POL" "Unterstützung RD" "VU" "Wasser in Gebäude" "Baum auf Straße")
		select alarmierung in "${options[@]}"
		do
			case $alarmierung in
				"Notfalltüröffnung")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Person eingeklemmt")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Person in Aufzug")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Person in Wasser")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Personensuche")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Schiffshavarie")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Tierrettung")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"TH Allgemein")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Unterstützung POL")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Unterstützung RD")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"VU")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Wasser in Gebäude")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Baum auf Straße")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				*) echo "Ungültige Option: $REPLY";;
			esac
		done
fi

if [[ $art == "Gefahrstoffe" ]]
	then
		#alarmierunggefahrstoffe
		echo "Einsatzstichwort: "
		PS3='Bitte auswählen: '
		options=("Auslaufende Gefahrstoffe" "CO2 Alarm" "Gasaustritt" "Gefahrstoffe Allgemein" "Unklarer Geruch")
		select alarmierung in "${options[@]}"
		do
			case $alarmierung in
				"Auslaufende Gefahrstoffe")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"CO2 Alarm")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Gasaustritt")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Gefahrstoffe Allgemein")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Unklarer Geruch")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;                        
				*) echo "Ungültige Option: $REPLY";;
			esac
		done
fi

if [[ $art == "Dienstleistung" ]]
	then
		#alarmierungdienstleistung
		echo "Einsatzstichwort: "
		PS3='Bitte auswählen: '
		options=("Brandsicherheitswache" "Dammwache" "Dienstleistung Allgemein" "Hydrantenpflege") 
		select alarmierung in "${options[@]}"
		do
			case $alarmierung in
				"Brandsicherheitswache")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Dammwache")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;
				"Dienstleistung Allgemein")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;    
				"Hydrantenpflege")
					echo "Du hast $alarmierung ausgewählt."
					break
					;;                                             
				*) echo "Ungültige Option: $REPLY";;
			esac
		done
fi

echo ""
echo "Bemerkungen : "
read bemerkungen
echo ""
echo ""

# übersicht eingegebene daten
echo "Übersicht Einsatz:"
echo "--------------------"
echo "Nummer: $nummer"
echo "Beginn: $beginn $beginnzeit"
echo "Ende: $ende $endzeit"
echo "Ort: $ort"
echo "Art: $art"
echo "Einsatzmittel: $einsatzmittel"
echo "Funktion: $funktion"
echo "Angeschnauft: $angeschnauft"
echo "AGT: $agt"
echo "Eingesetzt: $eingesetzt"
echo "Alarmierung: $alarmierung"
echo "Bemerkungen: $bemerkungen"
echo "--------------------"
echo ""
# Frage ob in DB schreiben
#agt
echo "In Datenbank schreiben?: "
PS3='Bitte auswählen: '
options=("OK" "Nee, doch nicht!")
select save in "${options[@]}"
do
    case $save in
        "OK")
            echo "Du hast $save ausgewählt."
	    echo ""		
	    echo "Schreibe Einsatz in Datenbank.."
			if [[ $funktion = AGT ]]
			then
			psql -P pager=off -d $database -U $username -c "INSERT INTO $database.einsaetze (nummer,start,ende,ort,art,funktion,eingesetzt,alarmierung,bemerkungen,einsatzmittel,angeschnauft,agt) VALUES ('$nummer', '$beginn $beginnzeit', '$ende $endzeit', '$ort', '$art', '$funktion', '$eingesetzt', '$alarmierung', '$bemerkungen', '$einsatzmittel', '$angeschnauft', '$agt');"
			else
			psql -P pager=off -d $database -U $username -c "INSERT INTO $database.einsaetze (nummer,start,ende,ort,art,funktion,eingesetzt,alarmierung,bemerkungen,einsatzmittel) VALUES ('$nummer', '$beginn $beginnzeit', '$ende $endzeit', '$ort', '$art', '$funktion', '$eingesetzt', '$alarmierung', '$bemerkungen', '$einsatzmittel');"
			fi
			# null von agt korrigieren
			if [[ $angeschnauft = false ]]
				then
				  psql -P pager=off -d $database -U $username -c "UPDATE $database.einsaetze SET "agt"=NULL WHERE "nummer"='$nummer';"
			fi
			# geschriebene daten von db lesen
			echo ""
			echo "Folgenden Einsatz erfolgreich in Datenbank geschrieben:"
			echo "----------------------"
			psql -P pager=off -d $database -U $username -c "SELECT * FROM $database.einsaetze WHERE nummer='$nummer';"
            break
            ;;
        "Nee, doch nicht!")
            echo "Breche ab und speichere nichts in die Datenbank."
            break
            ;;
        *) echo "Ungültige Option: $REPLY";;
    esac
done
