#!/bin/bash
#
# variablen
hostname=localhost
username=root
database=feuerwehr

echo "Letzter Meilenstein"
echo "-------------"
psql -P pager=off -d $database -U $username -c "SELECT * FROM meilensteine ORDER BY nummer DESC LIMIT 1;"
echo ""
echo ""
echo "Neuer Meilenstein"
echo "-------------"
echo ""

# einlesen der daten
echo "Meilenstein Nummer z.B. 4 : "
read nummer
echo "Datum z.B. 2019-05-25 :"
read datum
echo "Thema (Truppmann/AGT/Sprechfunker/etc.): "
read thema
echo "Bemerkungen : "
read bemerkungen
echo ""

# übersicht eingegebene daten
echo "Übersicht Meilenstein:"
echo "--------------------"
echo "Nummer: $nummer"
echo "Datum: $datum"
echo "Thema: $thema"
echo "Bemerkungen: $bemerkungen"
echo "--------------------"
echo ""

# Frage ob in DB schreiben
echo "In Datenbank schreiben?: "
PS3='Bitte auswählen: '
options=("OK" "Nee, doch nicht!")
select save in "${options[@]}"
do
    case $save in
        "OK")
            echo "Du hast $save ausgewählt."
	        echo ""		
	        echo "Schreibe Meilenstein in Datenbank.."
            psql -P pager=off -d $database -U $username -c "INSERT INTO meilensteine (nummer,date,thema,bemerkungen) VALUES ('$nummer', '$datum', '$thema', '$bemerkungen');"
			echo ""
			echo "Folgender Meilenstein erfolgreich in Datenbank geschrieben:"
			echo "----------------------"
			psql -P pager=off -d $database -U $username -c "SELECT * FROM meilensteine WHERE nummer='$nummer';"
            break
            ;;
        "Nee, doch nicht!")
            echo "Breche ab und speichere nichts in die Datenbank."
            break
            ;;
        *) echo "Ungültige Option: $REPLY";;
    esac
done
