#!/bin/bash
#
# variablen
hostname=localhost
username=root
database=feuerwehr

echo "Letzter Meilenstein"
echo "-------------"
psql -P pager=off -d $database -U $username -c "SELECT * FROM $database.meilensteine ORDER BY nummer DESC LIMIT 1;"
echo ""
echo ""
echo "Meilenstein entfernen"
echo "-------------"
echo ""

# einlesen der daten
echo "Meilenstein Nummer z.B. 4 : "
read nummer
echo ""

# übersicht eingegebene daten
echo "Ausgewählter Meilenstein zum löschen:"
echo "--------------------"
psql -P pager=off -d $database -U $username -c "SELECT * FROM $database.meilensteine WHERE nummer='$nummer';"
echo "--------------------"
echo ""

# Frage ob aus DB löschen
echo "Meilenstein löschen?: "
PS3='Bitte auswählen: '
options=("OK" "Nee, doch nicht!")
select save in "${options[@]}"
do
    case $save in
        "OK")
            echo "Du hast $save ausgewählt."
            echo ""		
            echo "Lösche Meilenstein aus Datenbank.."
            psql -P pager=off -d $database -U $username -c "DELETE FROM $database.meilensteine WHERE nummer='$nummer';"
            echo ""
            echo "Meilenstein gelöscht"
            echo "----------------------"
            break
            ;;
        "Nee, doch nicht!")
            echo "Breche ab und lösche nichts aus der Datenbank."
            break
            ;;
        *) echo "Ungültige Option: $REPLY";;
    esac
done
