#!/bin/bash
#
# variablen
hostname=localhost
username=root
database=feuerwehr
beginn=18:00:00
ende=19:30:00

echo "Letzte Übung"
echo "-------------"
psql $database $username << EOF
SELECT * FROM uebungen ORDER BY nummer DESC LIMIT 1;
EOF
echo ""
echo ""
echo "Neue Übung"
echo "-------------"
echo ""

# einlesen der daten
echo "Übung Nummer z.B. 4 : "
read nummer
echo "Datum in ISO z.B. 2019-05-25 :"
read datum 
echo "Ort z.B. Woerth :"
read ort
echo "Übungsthema: "
PS3='Bitte auswählen: '
options=("Unbekannt" "FwDV3" "FwDV10" "TH" "DLK" "PA" "Drohne" "Motorsäge" "Kaminbrand" "BMA" "Deiche" "AbstuSi" "Belüftung" "Alternative Antriebe" "Wasserrettung" "UVV" "Gefahrstoffe" "Jahreshauptübung" "Straßenbahn" "Putzen" "Sonstiges")
select art in "${options[@]}"
do
    case $art in
        "Unbekannt")
            echo "Du hast $art ausgewählt."
            break
            ;;
        "FwDV3")
            echo "Du hast $art ausgewählt."
            break
            ;;
        "FwDV10")
            echo "Du hast $art ausgewählt."
            break
            ;;
        "TH")
            echo "Du hast $art ausgewählt."
            break
            ;;            
        "DLK")
            echo "Du hast $art ausgewählt."
            break
            ;;
        "PA")
            echo "Du hast $art ausgewählt."
            break
            ;;
        "Drohne")
            echo "Du hast $art ausgewählt."
            break
            ;;
        "")
            echo "Du hast $art ausgewählt."
            break
            ;;            
        "")
            echo "Du hast $art ausgewählt."
            break
            ;;
        "")
            echo "Du hast $art ausgewählt."
            break
            ;;
        "")
            echo "Du hast $art ausgewählt."
            break
            ;;
        "")
            echo "Du hast $art ausgewählt."
            break
            ;;            
        "")
            echo "Du hast $art ausgewählt."
            break
            ;;
        "")
            echo "Du hast $art ausgewählt."
            break
            ;;
        "")
            echo "Du hast $art ausgewählt."
            break
            ;;
        "")
            echo "Du hast $art ausgewählt."
            break
            ;;            
        "")
            echo "Du hast $art ausgewählt."
            break
            ;;
        "")
            echo "Du hast $art ausgewählt."
            break
            ;;
        "")
            echo "Du hast $art ausgewählt."
            break
            ;;
        "")
            echo "Du hast $art ausgewählt."
            break
            ;;                                                
        *) echo "Ungültige Option: $REPLY";;
    esac
done
echo ""
echo "Teilnahme (true/false) : "
read teilnahme
echo "Bemerkungen : "
read bemerkungen
echo ""

# daten in db schreiben
echo "Schreibe Datensatz.."
echo "--------------------"
psql $database $username << EOF
INSERT INTO uebungen (nummer,start,ende,ort,thema,teilnahme,bemerkungen) VALUES ('$nummer', '$datum $beginn', '$datum $ende', '$ort', '$thema', '$teilnahme', '$bemerkungen');
EOF

# geschriebene daten von db lesen
echo "Fertiiiig. Guck, hier:"
echo "----------------------"
psql $database $username << EOF
SELECT * FROM uebungen WHERE nummer='$nummer';
EOF
