#!/bin/bash
#
# script by christian baumann
# https://christian-baumann.net
# https://gitlab.com/wurzelserver
#
# variablen
hostname=localhost
username=feuerwehr
database=feuerwehr

echo "Letzte Übung"
echo "-------------"
psql $database $username << EOF
SELECT * FROM uebungen ORDER BY nummer DESC LIMIT 1;
EOF
echo ""
echo ""
echo "Neue Übung"
echo "-------------"
echo ""

# einlesen der daten
echo "Übung Nummer z.B. 4 : "
read nummer
echo "Beginn z.B. 2019-05-25 04:57:17 :"
read beginn 
echo "Ende z.B. 2019-05-25 04:57:17 :"
read ende
echo "Ort z.B. Woerth :"
read ort
echo "Thema (Belüftung/FwDV3/TH/etc.): "
read thema
echo "Teilnahme (true/false) : "
read teilnahme

# daten in db schreiben
echo "Schreibe Datensatz.."
echo "--------------------"
psql $database $username << EOF
INSERT INTO uebungen (nummer,start,ende,ort,thema,teilnahme) VALUES ('$nummer', '$beginn', '$ende', '$ort', '$thema', '$teilnahme');
EOF

# geschriebene daten von db lesen
echo "Fertiiiig. Guck, hier:"
echo "----------------------"
psql $database $username << EOF
SELECT * FROM uebungen WHERE nummer='$nummer';
EOF
