#!/bin/bash
#
# script by christian baumann
# https://christian-baumann.net
# https://gitlab.com/wurzelserver
#
# variablen
hostname=localhost
username=feuerwehr
database=feuerwehr

echo "Letzte Übung"
echo "-------------"
psql $database $username << EOF
SELECT * FROM uebungen ORDER BY nummer DESC LIMIT 1;
EOF
echo ""
echo ""
echo "Übung entfernen"
echo "-------------"
echo ""

# einlesen der daten
echo "Übung Nummer z.B. 4 : "
read nummer

# daten in db schreiben
echo "Lösche Datensatz.."
echo "--------------------"
psql $database $username << EOF
DELETE FROM uebungen WHERE nummer='$nummer';
EOF
